In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
test_list = list(range(1000))
# list function is built-in to PYthon and will generate a list of integers from 0-1999

In [3]:
#create a numpy array
# the function i numpy that concominant to range in python is arange like a-range NOT ARRANGE
test_array = np.array(1000)
%timeit sum(test_list)
#a magic function that will time how long it takes to sum the 
# the numpy array is stored as an actual number array
# the python list is stored as seperate data bytes not connected to one another
#also the list elements in python have to be checked one by one to se if they are actual numbers
#the array already knows what it is a 64 bit integer and the calculation occurs in C++ 
# by getting the speed we are going to lose some flexibility a numpy array is not going to behave like a list
# a python LIST can contain data of different types,can be resized ie list.append, 
#the np array has to have all the same type of data and it is a fixed size


8.51 µs ± 178 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
%timeit np.sum(test_array)

5.08 µs ± 1.72 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
#this shows how numpy is faster than python ( between 10 to 100 times faster) true for any kind of arithmetic done 

In [6]:
a = np.array([-1,0, 1, 100], dtype = 'int8') # i want an 8 bit integer

In [7]:
a

array([ -1,   0,   1, 100], dtype=int8)

In [9]:
#a/0

In [10]:
100 ** 2

10000

In [11]:
a ** 2

array([ 1,  0,  1, 16], dtype=int8)

In [12]:
# ah 100 squared is not 16 , there is integer overflow because of the 8 bit space we allocated
# we are going to change the type of the number in the array
b = a.astype('float32')

In [13]:
b

array([ -1.,   0.,   1., 100.], dtype=float32)

In [14]:
b/0

C:\Users\mjc341\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\mjc341\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([-inf,  nan,  inf,  inf], dtype=float32)

In [15]:
np.nan == np.nan
#ask what is the np.nan is it the same thing as itself ...no because we don't know what it is
# so nan can't be found by regular nan techniuqes

False

In [16]:
#have to use isnan
# nan is not defined in the integers definition only in floats
np.isnan(np.nan)

True

Accessing numbers in NUMPY: putting them into the array , taking them out and performing calculations


In [17]:
np.zeros
#generate an array of zeros

<function numpy.core.multiarray.zeros>

In [18]:
np.ones
#generate and array of ones


<function numpy.core.numeric.ones(shape, dtype=None, order='C')>

In [19]:
np.empty
#generate an empty array
# this will make an array and temporarity fill it with whatever is in the space that np is creating the array in which will 
#will soon be replace with whatever you put into it its like holding some memory open and just showing you what happened to be in there

<function numpy.core.multiarray.empty>

In [20]:
np.empty((2,2))

array([[ -1.,   0.],
       [  1., 100.]])

In [21]:
a

array([ -1,   0,   1, 100], dtype=int8)

In [22]:
#how to I retrive data from an array its similar to lists with get item and slice
#0 indexed

In [23]:
# I will recieve the number extracted form the array, its no longer in the brackets
#this is the get item syntax
a[0]

-1

In [24]:
a[-1]

100

In [25]:
#now the slice syntax
# it will be returned as an array NOT a tuple or LIST
a[0:2]

array([-1,  0], dtype=int8)

In [26]:
#get a slice by steps same as list behavior
a[::2]

array([-1,  1], dtype=int8)

In [27]:
#can put use get item to insert numbers
a[-1]  = 5

In [28]:
a


array([-1,  0,  1,  5], dtype=int8)

In [29]:
#shows that arrays are mutable you can swap in data
# now a 2 dimensional np array

In [30]:
#create an array by np.arange and then add another step called .reshape so the one dimensional array of (0-11) 
# is reshped into 2 dimension these are NOT rows and columns this is because you can have 3 dimension, 4 dimensional etc
b = np.arange(12).reshape(4,3)

In [31]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
b.shape

(4, 3)

In [33]:
#use the get item syntax to retrieve a number from the 2 dimensional array
#get item calls will always collapse the dimension
b[2,2]

8

In [34]:
b[:2,:2]

array([[0, 1],
       [3, 4]])

In [35]:
#this collapses the 2 dimensional array into 1 dimension
b[1:3,-1]

array([5, 8])

In [36]:
#this preserves the 2 dimensions
b[1:3,-1:]

array([[5],
       [8]])

In [37]:
b[:1,:1]

array([[0]])

In [39]:
#to read csv files
#np.loadtxt has a skip row call wich will then not import the headers
np.loadtxt?

In [40]:
c = np.arange(24).reshape(2,3,4)

In [41]:
# these are stacked but cant display it as such on screen
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [42]:
# need to have 3 get item calls get the number 17
c[1,1,1]

17

In [43]:
#get the top array only as a one dimensional array NOTE you have to use 1 get item call to collapse the dimension
# the comma is a get item call the : is a slicing call
# you have to supply the number of operators equal to the number of dimension you have
c[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
c[1,0,:]

array([12, 13, 14, 15])

In [45]:
#turn it into a one dim
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [48]:
q = np.arange(25).reshape(5,5)

In [49]:
q

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
#top to bottom is the 1st ask and left to right is the second ask

q[4,:]

array([20, 21, 22, 23, 24])

In [53]:
q[:,1: :2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [ ]:
q[]